platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/ubuntu-gpdb-dev
    tag: '16.04_gcc_6_3'
inputs:
  - name: gpdb_src
  - name: compiled_bits_gpdb_with_orca_conan_ubuntu16
outputs:
  - name: icg_output
run:
  path: gpdb_src/concourse/scripts/test_gpdb.py
  args:
    - --mode=orca
    - --gpdb_name=compiled_bits_gpdb_with_orca_conan_ubuntu16
params:
  BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
  TEST_SUITE: "icw"
